# Generated by Django 2.2.6 on 2019-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_taxon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='id_endemia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='occ_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='plot_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
