# Generated by Django 2.2.6 on 2019-11-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_taxon', '0002_auto_20191031_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenology', models.CharField(max_length=15)),
                ('january', models.IntegerField(blank=True, null=True)),
                ('february', models.IntegerField(blank=True, null=True)),
                ('march', models.IntegerField(blank=True, null=True)),
                ('april', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('june', models.IntegerField(blank=True, null=True)),
                ('july', models.IntegerField(blank=True, null=True)),
                ('august', models.IntegerField(blank=True, null=True)),
                ('september', models.IntegerField(blank=True, null=True)),
                ('october', models.IntegerField(blank=True, null=True)),
                ('november', models.IntegerField(blank=True, null=True)),
                ('december', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon', to='data_taxon.Taxon')),
            ],
        ),
    ]
