# Generated by Django 2.2.12 on 2020-07-21 04:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_taxon', '0003_auto_20200716_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='plot_count',
            new_name='id_florical',
        ),
        migrations.AddField(
            model_name='taxon',
            name='bark_thickness_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='bark_thickness_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='bark_thickness_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='dbh_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='dbh_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='dbh_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='fleshy_fruit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='freq10_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='freq_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='freq_plot1ha_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='geo_pts_pn',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='taxon',
            name='height_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_area_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_area_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_area_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_ldmc_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_ldmc_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_ldmc_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_sla_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_sla_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_sla_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_thickness_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_thickness_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_thickness_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='leaf_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='ncpippn_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='occ_um_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='sexual_system',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='wood_density_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='wood_density_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='wood_density_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
