# Generated by Django 2.2.12 on 2020-07-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_taxon', '0004_auto_20200721_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
