# Generated by Django 2.2.12 on 2020-07-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_taxon', '0005_auto_20200721_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phenology',
        ),
    ]
