# Generated by Django 2.2.12 on 2020-04-01 23:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('sort', models.IntegerField()),
                ('height', models.CharField(choices=[('25', 'Small'), ('50', 'Medium'), ('75', 'Large'), ('100', 'XLarge')], default='25', max_length=3)),
                ('show', models.BooleanField(default=True)),
                ('profil', models.CharField(default='default', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('type_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('land_um_area', models.FloatField(blank=True, null=True)),
                ('forest_area', models.FloatField(blank=True, null=True)),
                ('forest_um_area', models.FloatField(blank=True, null=True)),
                ('forest_perimeter', models.FloatField(blank=True, null=True)),
                ('nb_patchs', models.IntegerField(blank=True, null=True)),
                ('nb_patchs_in', models.IntegerField(blank=True, null=True)),
                ('forest_in', models.FloatField(blank=True, null=True)),
                ('r_in_median', models.FloatField(blank=True, null=True)),
                ('nb_plots', models.IntegerField(blank=True, null=True)),
                ('nb_occurence', models.IntegerField(blank=True, null=True)),
                ('nb_families', models.IntegerField(blank=True, null=True)),
                ('nb_species', models.IntegerField(blank=True, null=True)),
                ('n_unique_species', models.IntegerField(blank=True, null=True)),
                ('fragment_meff_cbc', models.FloatField(blank=True, null=True)),
                ('um_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_object', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('class_value', models.FloatField()),
                ('param1_str', models.CharField(blank=True, max_length=30, null=True)),
                ('param2_str', models.CharField(blank=True, max_length=30, null=True)),
                ('param3_float', models.FloatField(blank=True, null=True)),
                ('param4_float', models.FloatField(blank=True, null=True)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequencies', to='data_shape.Shape')),
            ],
        ),
    ]
