# Generated by Django 2.2.7 on 2019-11-19 23:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='forest_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_perimeter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_um_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='n_unique_species',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_families',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_occurence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_patchs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_patchs_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_species',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='r_in_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='typeShape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='um_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='um_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='shape',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
