# Generated by Django 2.2.12 on 2020-04-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0004_auto_20200420_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='legend_locate',
            field=models.CharField(choices=[('right', 'right'), ('bottom', 'bottom')], default='bottom', max_length=10),
        ),
    ]
