# Generated by Django 2.2.12 on 2020-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0005_auto_20200420_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='legend_locate',
            field=models.CharField(choices=[('right', 'right'), ('bottom', 'bottom'), ('left', 'left'), ('top', 'top'), ('nolegend', 'nolegend')], default='bottom', max_length=10),
        ),
    ]
