# Generated by Django 2.2.7 on 2019-12-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0005_auto_20191212_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='height',
            field=models.CharField(choices=[('25', 'Small'), ('50', 'Medium'), ('75', 'Large'), ('100', 'XLarge')], default='25', max_length=3),
        ),
    ]
