# Generated by Django 2.2.9 on 2020-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0006_auto_20191212_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='um_area',
            new_name='land_um_area',
        ),
        migrations.AddField(
            model_name='shape',
            name='nb_plots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
