# Generated by Django 2.2.12 on 2020-05-17 22:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0006_auto_20200420_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='forest_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
