# Generated by Django 2.2.9 on 2020-03-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0007_auto_20200312_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='fragment_meff_cbc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
