# Generated by Django 2.2.12 on 2020-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0007_shape_forest_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='forest_300_600',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_cover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_cover_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_cover_um',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_heart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_holdridge1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_holdridge2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_holdridge3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_inf_300',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_mining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_ppe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_primary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_reserve',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_secondary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='forest_sup_600',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='land_holdridge1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='land_holdridge2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='land_holdridge3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='max_rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='min_rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='mining_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='mining_um_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='ppe_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='reserve_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='reserve_um_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
