# Generated by Django 2.2.12 on 2020-10-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0011_auto_20201008_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='forest_300_600',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_core',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_cover',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_cover_num',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_cover_um',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_holdridge1',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_holdridge2',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_holdridge3',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_inf_300',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_ppe',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_primary',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_secondary',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='forest_sup_600',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='land_holdridge1',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='land_holdridge2',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='land_holdridge3',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='max_rainfall',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='min_rainfall',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='mining_area',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='mining_um_area',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='ppe_area',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='reserve_area',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='reserve_um_area',
        ),
    ]
