# Generated by Django 2.2.12 on 2020-10-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0013_remove_shape_nb_patchs_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='forest_geom',
            new_name='geom_forest',
        ),
        migrations.RenameField(
            model_name='shape',
            old_name='um_geom',
            new_name='geom_um',
        ),
    ]
