# Generated by Django 2.2.12 on 2020-10-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0014_auto_20201022_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='r_in_median',
        ),
    ]
