# Generated by Django 2.2.12 on 2020-11-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0016_remove_shape_n_unique_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='elevation_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='elevation_median',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='rainfall_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shape',
            name='rainfall_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
