# Generated by Django 2.2.12 on 2020-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_shape', '0018_graph_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='information',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
