# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestfragment',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
