# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0003_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
