# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0005_plotoccurrences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotoccurrences',
            old_name='occurrence_id',
            new_name='occurrence',
        ),
        migrations.RenameField(
            model_name='plotoccurrences',
            old_name='plot_id',
            new_name='plot',
        ),
    ]
