# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0006_auto_20160809_1350'),
    ]

    operations = [
        migrations.DeleteModel("Occurrence"),
        migrations.DeleteModel("PlotOccurrences")
    ]
