# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 00:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0007_auto_20160810_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Taxon')),
            ],
        ),
        migrations.CreateModel(
            name='PlotOccurrences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Occurrence')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Plot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plotoccurrences',
            unique_together=set([('occurrence', 'plot')]),
        ),
    ]
