# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0009_auto_20160810_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceObservations',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='niamoto_data.Occurrence')),
                ('date', models.DateField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('stem_nb', models.IntegerField(blank=True, null=True)),
                ('circumference', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
