# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0010_occurrenceobservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
