# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0011_auto_20160915_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
