# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0013_auto_20161003_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceobservations',
            name='last_observation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
