# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0015_auto_20161108_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceobservations',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
