# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0016_occurrenceobservations_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
