# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0017_plot_elevation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrenceobservations',
            old_name='circumference',
            new_name='dbh',
        ),
    ]
