# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-19 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0018_auto_20161215_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceobservations',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
