# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0019_occurrenceobservations_rainfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='bark_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='dbh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='last_observation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='stem_nb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='wood_density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
