# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-26 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0021_remove_occurrence_last_observation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrenceobservations',
            name='occurrence',
        ),
        migrations.DeleteModel(
            name='OccurrenceObservations',
        ),
    ]
