# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-15 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0022_auto_20170627_0821'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taxon',
            managers=[
            ],
        ),
    ]
