# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-12 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0025_auto_20190605_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='basal_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='canopy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='dbh_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='dbh_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='dbh_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='dbh_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='emergent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='ferns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='h_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='lianas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='living_stems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='nb_families',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='nb_species',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='palms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='pielou',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='shannon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='simpson',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='species_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='strate_indet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='total_stems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='undercanopy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='understorey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
