# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-12 04:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0026_auto_20190612_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
