# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0027_auto_20190612_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
