# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0028_auto_20190613_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Plot'),
        ),
    ]
