# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 22:01
from __future__ import unicode_literals

from datetime import datetime

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models, transaction, connection
import django.db.models.deletion


@transaction.atomic
def migrate_rapid_inventories(apps, schema_editor):
    from apps.rapid_inventories.models import RapidInventory, Inventory
    sql = \
        """
        SELECT id, inventory_date, location, observer_id
        FROM {}
        """.format(RapidInventory._meta.db_table)
    cursor = connection.cursor()
    cursor.execute(sql)
    rapid_inventories = cursor.fetchall()
    for ri in rapid_inventories:
        Inventory.objects.create(
            id=ri[0],
            created_at=datetime.now(),
            updated_at=datetime.now(),
            inventory_date=ri[1],
            location=ri[2],
            observer_id=ri[3]
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapid_inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_date', models.DateField(verbose_name="Date de l'inventaire")),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Observateur')),
            ],
        ),
        migrations.RunPython(migrate_rapid_inventories),
    ]
