# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_taxainventory'),
        ('user_occurrences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroccurrence',
            name='observer',
        ),
        migrations.AddField(
            model_name='useroccurrence',
            name='taxa_inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventories.TaxaInventory'),
            preserve_default=False,
        ),
    ]
