# Generated by Django 2.2.12 on 2020-04-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='persons')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(choices=[('publication', 'publication'), ('book', 'livre'), ('report', 'rapport'), ('article', 'article'), ('conference', 'conférence'), ('film', 'film'), ('radio', 'radio')], default='publication', max_length=50)),
                ('who', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('journal', models.CharField(blank=True, max_length=250, null=True)),
                ('issue', models.CharField(blank=True, max_length=4, null=True)),
                ('pages', models.CharField(blank=True, max_length=12, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat', models.CharField(max_length=50)),
                ('first_year', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True)),
                ('first_month', models.IntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'aout'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True)),
                ('last_year', models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True)),
                ('last_month', models.IntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'aout'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True)),
                ('title', models.CharField(blank=True, default='.', max_length=210, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=850, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='portal.Person')),
            ],
            options={
                'verbose_name': 'acivity',
                'verbose_name_plural': 'activities',
            },
        ),
    ]
