# Generated by Django 2.2.12 on 2020-04-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_species', models.IntegerField(blank=True, null=True)),
                ('id_endemia', models.IntegerField(blank=True, null=True)),
                ('id_florical', models.IntegerField(blank=True, null=True)),
                ('id_family', models.IntegerField(blank=True, null=True)),
                ('id_infra', models.IntegerField(blank=True, null=True)),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
                ('species_name', models.CharField(blank=True, max_length=150, null=True)),
                ('infraspecies_name', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('statut', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
