# Generated by Django 2.2.12 on 2020-04-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='genre_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
