# Generated by Django 2.2.12 on 2020-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_tree_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='statut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
