# Generated by Django 2.2.9 on 2020-01-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_acivity_person_ressource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acivity',
            new_name='Activity',
        ),
    ]
