# Generated by Django 2.2.12 on 2020-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200403_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='permanent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
