# Generated by Django 2.2.9 on 2020-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200129_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='support',
            field=models.CharField(choices=[('publication', 'publication'), ('bool', 'livre'), ('report', 'rapport'), ('article', 'article'), ('communication', 'communication'), ('film', 'film'), ('radio', 'radio')], default='publication', max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True),
        ),
    ]
