# Generated by Django 2.2.12 on 2020-05-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_person_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='support',
            field=models.CharField(choices=[('publication', 'publication'), ('ouvrage', 'livre'), ('rapport', 'rapport'), ('article', 'article'), ('conference', 'conférence'), ('film', 'film'), ('radio', 'radio'), ('thèse', 'thèse'), ('mémoire', 'mémoire')], default='publication', max_length=50),
        ),
    ]
