# Generated by Django 2.2.12 on 2020-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200505_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='support',
            field=models.CharField(choices=[('publication', 'publication'), ('ouvrage', 'livre'), ('rapport', 'rapport'), ('article', 'article'), ('conférence', 'conférence'), ('film', 'film'), ('radio', 'radio'), ('thèse', 'thèse'), ('mémoire', 'mémoire')], default='publication', max_length=50),
        ),
    ]
