# Generated by Django 2.2.12 on 2020-05-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200505_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='out_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
