# Generated by Django 2.2.12 on 2020-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_activity_out_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='out_type',
            field=models.CharField(blank=True, choices=[('thèse', 'thèse'), ('mémoire', 'mémoires')], max_length=50, null=True),
        ),
    ]
