# Generated by Django 2.2.9 on 2020-01-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200129_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='first_month',
            field=models.IntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'aout'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='last_month',
            field=models.IntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'aout'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='.', max_length=150, null=True),
        ),
    ]
