# Generated by Django 2.2.9 on 2020-01-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200129_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
