# Generated by Django 2.2.12 on 2020-05-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200506_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='out_type',
            new_name='support',
        ),
    ]
