# Generated by Django 2.2.9 on 2020-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20200130_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=850, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='.', max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='who',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
