# Generated by Django 2.2.12 on 2020-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20200506_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
