# Generated by Django 2.2.12 on 2020-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_person_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='speciality',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
