# Generated by Django 2.2.9 on 2020-03-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20200204_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='issue',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ressource',
            name='journal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ressource',
            name='pages',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
