# Generated by Django 2.2.9 on 2020-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200302_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='support',
            field=models.CharField(choices=[('publication', 'publication'), ('book', 'livre'), ('report', 'rapport'), ('article', 'article'), ('conference', 'conférence'), ('film', 'film'), ('radio', 'radio')], default='publication', max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, null=True),
        ),
    ]
