# Generated by Django 2.2.12 on 2020-11-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200507_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='genre_name',
            new_name='genus_name',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='id_family',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='id_infra',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='id_species',
        ),
    ]
