# Generated by Django 2.2.12 on 2020-11-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Faq',
        ),
    ]
