# Generated by Django 2.2.12 on 2020-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20201116_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='ask',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(default='', max_length=200),
        ),
    ]
