# Generated by Django 2.2.12 on 2020-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_siteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='dateUpdateData',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
