# Generated by Django 2.2.12 on 2020-11-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201118_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
