# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20161102_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapidinventory',
            name='inventory_ptr',
            field=models.OneToOneField(auto_created=True, db_column='inventory_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.Inventory'),
        ),
    ]
