# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20161103_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapidinventory',
            name='location_description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='location_description',
            field=models.TextField(blank=True, null=True, verbose_name='Localité (Commune, Tribu, Lieu dit, ...)'),
        ),
    ]
