# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20161103_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaInventory',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.Inventory')),
            ],
            bases=('inventories.inventory',),
        ),
    ]
