# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_taxainventory'),
        ('inventories', '0006_auto_20161108_1108'),
    ]

    operations = [
    ]
