# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0014_auto_20161004_1732'),
        ('inventories', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaInventoryOccurrence',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='niamoto_data.Occurrence')),
                ('input_date', models.DateTimeField()),
                ('taxa_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.TaxaInventory')),
            ],
            bases=('niamoto_data.occurrence',),
        ),
    ]
