# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_taxainventoryoccurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxainventoryoccurrence',
            name='input_date',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
