# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_auto_20161108_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxainventory',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='taxainventoryoccurrence',
            name='taxa_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='inventories.TaxaInventory'),
        ),
    ]
