# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0012_auto_20170629_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxainventorytaxon',
            name='taxa_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.TaxaInventory'),
        ),
        migrations.AlterField(
            model_name='taxainventorytaxon',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxa', to='niamoto_data.Taxon'),
        ),
    ]
