# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-30 05:43
from __future__ import unicode_literals

import apps.inventories.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0014_auto_20170629_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxainventorytaxon',
            name='taxon_id_no_constraint',
            field=models.IntegerField(default=0, verbose_name=apps.inventories.models.TaxaInventory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxainventorytaxon',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Taxon'),
        ),
    ]
