# Generated by Django 2.2.12 on 2020-04-01 23:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('sort', models.IntegerField()),
                ('height', models.CharField(choices=[('25', 'Small'), ('50', 'Medium'), ('75', 'Large'), ('100', 'XLarge')], default='25', max_length=2)),
                ('show', models.BooleanField(default=True)),
                ('profil', models.CharField(default='default', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('species_level', models.FloatField(blank=True, null=True)),
                ('total_stems', models.IntegerField(blank=True, null=True)),
                ('living_stems', models.IntegerField(blank=True, null=True)),
                ('count_families', models.IntegerField(blank=True, null=True)),
                ('count_species', models.IntegerField(blank=True, null=True)),
                ('shannon', models.FloatField(blank=True, null=True)),
                ('pielou', models.FloatField(blank=True, null=True)),
                ('simpson', models.FloatField(blank=True, null=True)),
                ('basal_area', models.FloatField(blank=True, null=True)),
                ('h_mean', models.FloatField(blank=True, null=True)),
                ('dbh_mean', models.FloatField(blank=True, null=True)),
                ('dbh_median', models.FloatField(blank=True, null=True)),
                ('dbh_min', models.FloatField(blank=True, null=True)),
                ('dbh_max', models.FloatField(blank=True, null=True)),
                ('wood_density', models.FloatField(blank=True, null=True)),
                ('biomasse', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_object', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('class_value', models.FloatField()),
                ('param1_str', models.CharField(blank=True, max_length=30, null=True)),
                ('param2_str', models.CharField(blank=True, max_length=30, null=True)),
                ('param3_float', models.FloatField(blank=True, null=True)),
                ('param4_float', models.FloatField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequencies', to='data_plot.Plot')),
            ],
        ),
    ]
