# Generated by Django 2.2.12 on 2020-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
