# Generated by Django 2.2.6 on 2019-10-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='name',
            new_name='class_object',
        ),
    ]
