# Generated by Django 2.2.6 on 2019-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0002_auto_20191017_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('height', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], max_length=2)),
                ('show', models.BooleanField(default=True)),
                ('profil', models.CharField(default='default', max_length=30)),
            ],
        ),
    ]
