# Generated by Django 2.2.6 on 2019-10-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0003_graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='class_data',
            new_name='class_value',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='order',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='frequency',
            name='id_plot',
            field=models.IntegerField(),
        ),
    ]
