# Generated by Django 2.2.6 on 2019-10-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0003_graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='name',
            new_name='label',
        ),
    ]
