# Generated by Django 2.2.12 on 2020-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0004_auto_20200813_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='class_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
