# Generated by Django 2.2.6 on 2019-10-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0004_auto_20191021_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='class_data',
            new_name='class_value',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='order',
            new_name='sort',
        ),
    ]
