# Generated by Django 2.2.6 on 2019-10-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0005_auto_20191024_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequencies', to='data_plot.Plot'),
        ),
    ]
