# Generated by Django 2.2.12 on 2020-09-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0005_frequency_class_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='holdridge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='rainfall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='um_substrat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
