# Generated by Django 2.2.6 on 2019-10-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_plot', '0005_auto_20191021_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='id_plot',
            field=models.IntegerField(),
        ),
    ]
