# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:47
from __future__ import unicode_literals

import apps.forest_digitizing.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niamoto_data', '0002_forestfragment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizingProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('problem', models.CharField(max_length=255, null=True)),
                ('comments', models.TextField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForestFragment30k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ForestFragment3k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_fragments3k', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MassifAssignation',
            fields=[
                ('massif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assignation', serialize=False, to='niamoto_data.Massif')),
                ('status', models.IntegerField(choices=[(0, 'Non digitalisé'), (1, 'En cours'), (2, 'A valider')], default=0)),
                ('spatialite_file', models.FileField(null=True, storage=apps.forest_digitizing.models.OverwriteStorage(), upload_to='spatialite_files')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forestfragment3k',
            name='massif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Massif'),
        ),
        migrations.AddField(
            model_name='forestfragment3k',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_fragments3k', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forestfragment30k',
            name='massif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Massif'),
        ),
        migrations.AddField(
            model_name='digitizingproblem',
            name='massif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niamoto_data.Massif'),
        ),
        migrations.AddField(
            model_name='digitizingproblem',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
