# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_digitizing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizingproblem',
            name='uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='forestfragment30k',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='forestfragment3k',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
