# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 23:38
from __future__ import unicode_literals

import apps.forest_digitizing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_digitizing', '0002_auto_20160719_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massifassignation',
            name='spatialite_file',
            field=models.FileField(blank=True, null=True, storage=apps.forest_digitizing.models.OverwriteStorage(), upload_to='spatialite_files'),
        ),
    ]
