# coding: utf-8


VERBOSE_NAMES = {
    'inventory_date': "Date de l'inventaire",
    'observer': "Observateur",
    'location': "Localisation",
    'location_description': "Localité (Commune, Tribu, Lieu dit, ...)",
    'topography': "Position topographique",
    'diameters_diff_or_same': "Diamètres: avez-vous l'impression que les arbres ont",
    'little_diam_nb': "Combien d'arbres de petit diamètre observez-vous? (<= 1 main ou 20cm)",
    'big_diam_nb': "Combien d'arbres de gros diamètre observez-vous? (> 3 mains ou 60cm)",
    'biggest_tree_in_hands': "Arbre le plus gros de la placette en nombre de mains",
    'canopy_density': "Qualifiez la densité du couvert de la canopée",
    'regeneration_appearance': "La régénération vous semble t-elle",
    'regen_diff_leaves': "Diversité de la régénération - Estimez le nombre d'espèces différentes parmi les individus constituant la régénération?",
    'pres_palm_tree': "Palmiers",
    'presence_liana': "Lianes",
    'presence_arb_fern': "Fougères arborescentes",
    'presence_other_fern': "Autres fougères",
    'presence_niaouli': "Niaouli",
    'presence_tamanou': "Tamanou",
    'presence_kaori': "Kaori",
    'presence_columnaris_pine': "Pin colonnaire",
    'presence_pandanus': "Pandanus",
    'presence_banian': "Banian",
    'presence_houp': "Houp",
    'dominating_specie': "Une espèce vous semble t-elle dominante sur la placette?",
    'flowers': "Observez-vous des arbres en fleur ou en fruit?",
    'dead_trees_on_ground': "Nombre d'arbres morts au sol",
    'dead_trees_on_root': "Voyez-vous des arbres morts sur pied",
    'fire_marks': "Voyez-vous des traces de feu?",
    'lumberjack_marks': "Voyez-vous des traces de bucheronnage?",
    'machete_marks': "Voyez-vous des traces de sabres",
    'invasive_species': "Voyez-vous des espèces végétales exotique envahissantes?",
    'stag_marks': "Voyez-vous des traces de cerf?",
    'pig_marks': "Voyez-vous des traces de cochon?",
    'electric_ant_marks': "Voyez-vous des traces de fourmis électriques?",
    'other_observations': "Autres observations",
}
