# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import apps.niamoto_plantnote.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantnoteDatabase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('last_activated_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, storage=apps.niamoto_plantnote.models.OverwriteStorage(), upload_to=apps.niamoto_plantnote.models.plantnote_database_path)),
            ],
        ),
    ]
