# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_plantnote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantnotedatabase',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
