# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_data', '0011_auto_20160915_1118'),
        ('niamoto_plantnote', '0002_plantnotedatabase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantnoteOccurrence',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='niamoto_data.Occurrence')),
                ('plantnote_id', models.IntegerField(unique=True)),
                ('collector', models.CharField(max_length=300)),
            ],
            bases=('niamoto_data.occurrence',),
        ),
    ]
