# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niamoto_plantnote', '0003_plantnoteoccurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantnoteoccurrence',
            name='collector',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
